package frc.robot.superstructure;

import static frc.robot.superstructure.Constants.*;

public enum State {
    INTAKE(INTAKE_ELEVATOR_HEIGHT, INTAKE_ARM_ANGLE, INTAKE_CORAL_WHEELS_VOLTAGE, INTAKE_ALGAE_WHEELS_VOLTAGE),

    PRE_L1(PRE_L1_ELEVATOR_HEIGHT, PRE_L1_ARM_ANGLE, PRE_L1_CORAL_WHEELS_VOLTAGE, PRE_L1_ALGAE_WHEELS_VOLTAGE),
    L1(L1_ELEVATOR_HEIGHT, L1_ARM_ANGLE, L1_CORAL_WHEELS_VOLTAGE, L1_ALGAE_WHEELS_VOLTAGE),
    POST_L1(POST_L1_ELEVATOR_HEIGHT, POST_L1_ARM_ANGLE, POST_L1_CORAL_WHEELS_VOLTAGE, POST_L1_ALGAE_WHEELS_VOLTAGE),

    PRE_L2(PRE_L2_ELEVATOR_HEIGHT, PRE_L2_ARM_ANGLE, PRE_L2_CORAL_WHEELS_VOLTAGE, PRE_L2_ALGAE_WHEELS_VOLTAGE),
    L2(L2_ELEVATOR_HEIGHT, L2_ARM_ANGLE, L2_CORAL_WHEELS_VOLTAGE, L2_ALGAE_WHEELS_VOLTAGE),
    POST_L2(POST_L2_ELEVATOR_HEIGHT, POST_L2_ARM_ANGLE, POST_L2_CORAL_WHEELS_VOLTAGE, POST_L2_ALGAE_WHEELS_VOLTAGE),

    PRE_L3(PRE_L3_ELEVATOR_HEIGHT, PRE_L3_ARM_ANGLE, PRE_L3_CORAL_WHEELS_VOLTAGE, PRE_L3_ALGAE_WHEELS_VOLTAGE),
    L3(L3_ELEVATOR_HEIGHT, L3_ARM_ANGLE, L3_CORAL_WHEELS_VOLTAGE, L3_ALGAE_WHEELS_VOLTAGE),
    POST_L3(POST_L3_ELEVATOR_HEIGHT, POST_L3_ARM_ANGLE, POST_L3_CORAL_WHEELS_VOLTAGE, POST_L3_ALGAE_WHEELS_VOLTAGE),

    PRE_L4(PRE_L4_ELEVATOR_HEIGHT, PRE_L4_ARM_ANGLE, PRE_L4_CORAL_WHEELS_VOLTAGE, PRE_L4_ALGAE_WHEELS_VOLTAGE),
    L4(L4_ELEVATOR_HEIGHT, L4_ARM_ANGLE, L4_CORAL_WHEELS_VOLTAGE, L4_ALGAE_WHEELS_VOLTAGE),
    POST_L4(POST_L4_ELEVATOR_HEIGHT, POST_L4_ARM_ANGLE, POST_L4_CORAL_WHEELS_VOLTAGE, POST_L4_ALGAE_WHEELS_VOLTAGE),

    INTAKE_ALGAE2(INTAKE_ALGAE2_ELEVATOR_HEIGHT, INTAKE_ALGAE2_ARM_ANGLE, INTAKE_ALGAE2_CORAL_WHEELS_VOLTAGE, INTAKE_ALGAE2_ALGAE_WHEELS_VOLTAGE),
    INTAKE_ALGAE3(INTAKE_ALGAE3_ELEVATOR_HEIGHT, INTAKE_ALGAE3_ARM_ANGLE, INTAKE_ALGAE3_CORAL_WHEELS_VOLTAGE, INTAKE_ALGAE3_ALGAE_WHEELS_VOLTAGE),

    PRE_PROCESSOR(PRE_PROCESSOR_ELEVATOR_HEIGHT, PRE_PROCESSOR_ARM_ANGLE, PRE_PROCESSOR_CORAL_WHEELS_VOLTAGE, PRE_PROCESSOR_ALGAE_WHEELS_VOLTAGE),
    PROCESSOR(PROCESSOR_ELEVATOR_HEIGHT, PROCESSOR_ARM_ANGLE, PROCESSOR_CORAL_WHEELS_VOLTAGE, PROCESSOR_ALGAE_WHEELS_VOLTAGE),
    POST_PROCESSOR(POST_PROCESSOR_ELEVATOR_HEIGHT, POST_PROCESSOR_ARM_ANGLE, POST_PROCESSOR_CORAL_WHEELS_VOLTAGE, POST_PROCESSOR_ALGAE_WHEELS_VOLTAGE),

    PRE_NET(PRE_NET_ELEVATOR_HEIGHT, PRE_NET_ARM_ANGLE, PRE_NET_CORAL_WHEELS_VOLTAGE, PRE_NET_ALGAE_WHEELS_VOLTAGE),
    NET(NET_ELEVATOR_HEIGHT, NET_ARM_ANGLE, NET_CORAL_WHEELS_VOLTAGE, NET_ALGAE_WHEELS_VOLTAGE),
    POST_NET(POST_NET_ELEVATOR_HEIGHT, POST_NET_ARM_ANGLE, POST_NET_CORAL_WHEELS_VOLTAGE, POST_NET_ALGAE_WHEELS_VOLTAGE),

    DEFAULT(DEFAULT_ELEVATOR_HEIGHT, DEFAULT_ARM_ANGLE, DEFAULT_CORAL_WHEELS_VOLTAGE, DEFAULT_ALGAE_WHEELS_VOLTAGE),
    ALGAE_DEFAULT(ALGAE_DEFAULT_ELEVATOR_HEIGHT, ALGAE_DEFAULT_ARM_ANGLE, ALGAE_DEFAULT_CORAL_WHEELS_VOLTAGE, ALGAE_DEFAULT_ALGAE_WHEELS_VOLTAGE),
    AUTOMATION_DEFAULT(AUTOMATION_DEFAULT_ELEVATOR_HEIGHT, AUTOMATION_DEFAULT_ARM_ANGLE, AUTOMATION_DEFAULT_CORAL_WHEELS_VOLTAGE, AUTOMATION_DEFAULT_ALGAE_WHEELS_VOLTAGE);

    public final double m_elevatorHeight,
            m_armAngle,
            m_coralVoltage,
            m_algaeVoltage;



    State(
            double elevatorHeight,
            double armAngle,
            double coralVoltage,
            double algaeVoltage
    ) {
        m_elevatorHeight = elevatorHeight;
        m_armAngle = armAngle;
        m_coralVoltage = coralVoltage;
        m_algaeVoltage = algaeVoltage;

    }
}

