package frc.robot.superstructure;

import static frc.robot.superstructure.Constants.*;

public enum State {
    INTAKE(INTAKE_ELEVATOR_HEIGHT, INTAKE_ARM_ANGLE, INTAKE_CORAL_WHEELS_VOLTAGE, INTAKE_ALGAE_WHEELS_VOLTAGE),
    L1(L1_ELEVATOR_HEIGHT, L1_ARM_ANGLE, L1_CORAL_WHEELS_VOLTAGE, L1_ALGAE_WHEELS_VOLTAGE),
    L2(L2_ELEVATOR_HEIGHT, L2_ARM_ANGLE, L2_CORAL_WHEELS_VOLTAGE, L2_ALGAE_WHEELS_VOLTAGE),
    L3(L3_ELEVATOR_HEIGHT, L3_ARM_ANGLE, L3_CORAL_WHEELS_VOLTAGE, L3_ALGAE_WHEELS_VOLTAGE),
    L4(L4_ELEVATOR_HEIGHT, L4_ARM_ANGLE, L4_CORAL_WHEELS_VOLTAGE, L4_ALGAE_WHEELS_VOLTAGE),
    PRE_L1(L1_ELEVATOR_HEIGHT, L1_ARM_ANGLE, DEFAULT_CORAL_WHEELS_VOLTAGE, DEFAULT_ALGAE_WHEELS_VOLTAGE),
    PRE_L2(L2_ELEVATOR_HEIGHT, L2_ARM_ANGLE, DEFAULT_CORAL_WHEELS_VOLTAGE, DEFAULT_ALGAE_WHEELS_VOLTAGE),
    PRE_L3(L3_ELEVATOR_HEIGHT, L3_ARM_ANGLE, DEFAULT_CORAL_WHEELS_VOLTAGE, DEFAULT_ALGAE_WHEELS_VOLTAGE),
    PRE_L4(L4_ELEVATOR_HEIGHT, L4_ARM_ANGLE, DEFAULT_CORAL_WHEELS_VOLTAGE, DEFAULT_ALGAE_WHEELS_VOLTAGE),
    POST_L1(L1_ELEVATOR_HEIGHT, L1_ARM_ANGLE, DEFAULT_CORAL_WHEELS_VOLTAGE, DEFAULT_ALGAE_WHEELS_VOLTAGE),
    POST_L2(L2_ELEVATOR_HEIGHT, L2_ARM_ANGLE, DEFAULT_CORAL_WHEELS_VOLTAGE, DEFAULT_ALGAE_WHEELS_VOLTAGE),
    POST_L3(L3_ELEVATOR_HEIGHT, L3_ARM_ANGLE, DEFAULT_CORAL_WHEELS_VOLTAGE, DEFAULT_ALGAE_WHEELS_VOLTAGE),
    POST_L4(L4_ELEVATOR_HEIGHT, L4_ARM_ANGLE+0.2, L4_CORAL_WHEELS_VOLTAGE, DEFAULT_ALGAE_WHEELS_VOLTAGE),
    ALGAE2(ALGAE2_ELEVATOR_HEIGHT, ALGAE2_ARM_ANGLE, ALGAE2_CORAL_WHEELS_VOLTAGE, ALGAE2_ALGAE_WHEELS_VOLTAGE),
    ALGAE3(ALGAE3_ELEVATOR_HEIGHT, ALGAE3_ARM_ANGLE, ALGAE3_CORAL_WHEELS_VOLTAGE, ALGAE3_ALGAE_WHEELS_VOLTAGE),
    EJECT(EJECT_CORAL_ELEVATOR_HEIGHT, EJECT_CORAL_ARM_ANGLE, EJECT_CORAL_CORAL_WHEELS_VOLTAGE, EJECT_CORAL_ALGAE_WHEELS_VOLTAGE),
    DEFAULT(DEFAULT_ELEVATOR_HEIGHT, DEFAULT_ARM_ANGLE, DEFAULT_CORAL_WHEELS_VOLTAGE, DEFAULT_ALGAE_WHEELS_VOLTAGE),
    AUTO(L1_ELEVATOR_HEIGHT, -1.27, 9, L1_ALGAE_WHEELS_VOLTAGE);

    public final double m_elevatorHeight,
            m_armAngle,
            m_coralVoltage,
            m_algaeVoltage;

    State(
            double elevatorHeight,
            double armAngle,
            double coralVoltage,
            double algaeVoltage
    ) {
        m_elevatorHeight = elevatorHeight;
        m_armAngle = armAngle;
        m_coralVoltage = coralVoltage;
        m_algaeVoltage = algaeVoltage;
    }
}

